server:
  port: 8453
  ssl:
    key-store: file:/Users/tjikaljedy/Workspace/SSL/dev/melody-io.p12
    key-store-password: changeit
---
core-config:
  core-rsocket:
    enabled: true
    uri: ws://127.0.0.1:6565/ws